//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineAttendance.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class attendance
    {
        public int sno { get; set; }
        public string stid { get; set; }
        public string name { get; set; }
        public string date { get; set; }
        public string subject { get; set; }
        public string markedBy { get; set; }
        public string status { get; set; }
    }
}
